# Generated by Django 4.0.1 on 2022-03-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_econtact_alter_employee_eemial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eemial',
            field=models.CharField(max_length=100),
        ),
    ]
